"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Message = { role: "user" | "assistant"; content: string; created_at: string };

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const [loading, setLoading] = useState(false); const bottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, loading]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!text.trim()) return; const current = text.trim(); setText(""); setMessages((items) => [...items, { role: "user", content: current, created_at: new Date().toISOString() }]); setLoading(true); const token = localStorage.getItem("token"); const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"}/api/v1/conversations/1/messages`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ content: current }) }); const data = await response.json(); setMessages((items) => [...items, { role: "assistant", content: data.content ?? "Unable to respond.", created_at: new Date().toISOString() }]); setLoading(false); }
  return <main className="flex min-h-screen flex-col bg-slate-950 text-slate-100"><header className="border-b border-white/10 px-6 py-5"><h1 className="text-xl font-bold">KelanaAI Chat</h1><p className="text-sm text-slate-400">Travel conversation</p></header><section className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-4 overflow-y-auto px-6 py-8">{messages.length === 0 && <p className="text-center text-slate-500">Start a conversation about your next trip.</p>}{messages.map((message, index) => <div key={`${message.created_at}-${index}`} className={`max-w-[85%] rounded-2xl px-4 py-3 ${message.role === "user" ? "self-end bg-cyan-300 text-slate-950" : "bg-slate-800 text-slate-100"}`}><p className="whitespace-pre-line">{message.content}</p><time className="mt-2 block text-xs opacity-60">{new Date(message.created_at).toLocaleTimeString()}</time></div>)}{loading && <div className="self-start rounded-2xl bg-slate-800 px-4 py-3 text-sm text-slate-400">AI is typing...</div>}<div ref={bottomRef} /></section><form onSubmit={submit} className="mx-auto flex w-full max-w-3xl gap-3 px-6 pb-8"><input className="flex-1 rounded-xl border border-white/10 bg-slate-800 px-4 py-3 outline-none focus:border-cyan-300" placeholder="Type a message..." value={text} onChange={(e) => setText(e.target.value)} /><button className="rounded-xl bg-cyan-300 px-5 font-semibold text-slate-950">Send</button></form></main>;
}
